version: '3.8'

services:
  bot:
    build:
      context: .
    env_file: .env
    restart: unless-stopped
  redis:
    # container_name: redis
    image: redis:7.0
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.docker_data/redis:/data